# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Mark J. Hulme
description: Architect, Accessibility Specialist 
github_username: markjhulme

# Email and twitter are optional:
email: 
twitter_username: archifilter

# Set this to true to get LaTeX math equation support
use_math: 

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
  
#----  
 
#theme: jekyll-agency

#remote_theme: raviriley/agency-jekyll-theme

#url    : "http://markjhulme.com" # the base hostname & protocol for your site, e.g. http://example.com
#baseurl: "" # the subpath of your site, e.g. /blog

#title      : Mark J. Hulme
#email      : mark@markjhulme.com #this is also the email contact forms will go to
#description: "Agency Bootstrap theme converted to a Jekyll theme, plus new features: Google Analytics, Markdown support, custom pages, and more!"
#author     : Mark J. Hulme
# logo:     #optional, defaults to site title
  # path: assets\img\clients\creative-market.jpg
  # height: 60 #height in px, defaults to 52px

#analytics:
#  google: #Google Analytics tracking code here

#collections:
#  portfolio:

#markdown: kramdown

#plugins:
#  - jekyll-remote-theme
